version: '3.7'

services:
  db:
    image: postgres
    container_name: database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: campaigns_db
    restart: always

  web:
    build: ./src
    container_name: backend
    volumes:
      - ./src/:/code/
    depends_on:
      - db
    restart: always

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./src/monolith/static:/code/static
      - ./src/monolith/media:/code/media
      - ./config/nginx/conf/campaigns.conf:/etc/nginx/conf.d/campaigns.conf
    depends_on:
      - web

volumes:
  db-data:
    driver: local