# Generated by Django 2.2.4 on 2019-08-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification_card',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cédula'),
        ),
    ]
