# Generated by Django 2.2.4 on 2019-08-24 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre municipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_code', models.CharField(max_length=3, verbose_name='ISO 3166-1 numerico')),
                ('alfa_two', models.CharField(max_length=2, verbose_name='ISO 3166-1 alfa-2')),
                ('alfa_three', models.CharField(max_length=3, verbose_name='ISO 3166-1 alfa-3')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre del país')),
                ('phone_code', models.CharField(max_length=5, verbose_name='Código número telefónico')),
                ('icon', models.ImageField(upload_to='country_icon/', verbose_name='Icono del país')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Zona')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.City', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='VotingPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Puesto de votación')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Neighborhood', verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Puesto de votación',
                'verbose_name_plural': 'Puestos de votaciones',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre del departamento')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='zone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Zone', verbose_name='Zona'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Region', verbose_name='Departamento'),
        ),
    ]
