# Generated by Django 2.2.4 on 2019-08-24 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='candidature',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='campaigns.Campaign', verbose_name='Candidatura'),
            preserve_default=False,
        ),
    ]
