# Generated by Django 2.2.4 on 2019-08-26 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20190825_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpeople',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign', verbose_name='Campaña o candidatura'),
        ),
        migrations.AlterField(
            model_name='listpeople',
            name='id_list',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de la planilla'),
            preserve_default=False,
        ),
    ]
