# Generated by Django 2.2.4 on 2019-09-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_listpeople_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpeople',
            name='id_list',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de la planilla'),
        ),
    ]
