# Generated by Django 2.2.4 on 2019-09-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20190901_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyed',
            unique_together={('person', 'list_people')},
        ),
    ]
